<a href="https://colab.research.google.com/github/realalyeasin/Deep-Learning/blob/main/TensorFlow_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Introducion to TensorFlow***
---

---



*   Intro
*   Info
*   Manipulating
*   Numpy
*   @tf.function
*   GPU







***Intro***

In [1]:
#Importing
import tensorflow as tf
print(tf.__version__)

2.8.0


***Creating tensors with tf.constant()***

In [2]:
scaler = tf.constant(120)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [3]:
scaler.ndim

0

In [4]:
vector = tf.constant([76,79,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([76, 79, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[263,726,917],[625,27,182]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[263, 726, 917],
       [625,  27, 182]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[11,12,13],
                       [71,52,43]],
                      [[22,44,36],
                       [22,54,32]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [71, 52, 43]],

       [[22, 44, 36],
        [22, 54, 32]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
x = tf.Variable([100,200,300])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300], dtype=int32)>

In [11]:
x[2].assign(250)
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 250], dtype=int32)>

***Random Tensor***

In [12]:
x1 = tf.random.Generator.from_seed(10)
x1 = x1.normal(shape=(2,1,4))
x2 = tf.random.Generator.from_seed(10)
x2 = x2.normal(shape=(2,1,4))

In [13]:
x1, x2, x1 == x2

(<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True]],
 
        [[ True,  True,  True,  True]]])>)

***Shuffle***

In [14]:
tf.random.set_seed(42)
tf.random.shuffle(x1)

<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
array([[[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],

       [[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]]],
      dtype=float32)>

In [15]:
tf.ones([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.zeros([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

***Numpy Array into Tensor***

In [17]:
import numpy as np
numpy_A = np.arange(1,20,2, dtype=np.int32)
numpy_A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int32)

In [18]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,5))

***Info***
* Shape
* Rank
* Axis
* Size

In [19]:
A = tf.ones(shape=[2,3,5,8])
A

<tf.Tensor: shape=(2, 3, 5, 8), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.,

In [20]:
print("Datatype", A.dtype)
print("Dimensions", A.ndim)
print("Shape", A.shape)
print("0 Axis", A.shape[0])
print("Last Axis", A.shape[-1])
print("Total Elements", tf.size(A))
print("Total Elements", tf.size(A).numpy())

Datatype <dtype: 'float32'>
Dimensions 4
Shape (2, 3, 5, 8)
0 Axis 2
Last Axis 8
Total Elements tf.Tensor(240, shape=(), dtype=int32)
Total Elements 240


***Indexing***

In [31]:
a = np.random.randint(5,100, size=24)
tf.constant(a)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([40, 21, 27, 26, 54, 34, 96, 77, 65, 67, 71, 27, 71, 45, 18, 74, 71,
       94, 49, 56, 11, 53, 23, 26])>

In [32]:
a[:6]

array([40, 21, 27, 26, 54, 34])

In [54]:
A = tf.constant(a, shape=[2,4,3])
A

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[40, 21, 27],
        [26, 54, 34],
        [96, 77, 65],
        [67, 71, 27]],

       [[71, 45, 18],
        [74, 71, 94],
        [49, 56, 11],
        [53, 23, 26]]])>

In [55]:
A[:1,-1,:2]

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[67, 71]])>

In [56]:
A[:1, -2, -2]

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([77])>

In [57]:
A[:1, -2]

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[96, 77, 65]])>

In [58]:
A[:1,:,:1]

<tf.Tensor: shape=(1, 4, 1), dtype=int64, numpy=
array([[[40],
        [26],
        [96],
        [67]]])>

In [59]:
A[:,-1,-1]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([27, 26])>

In [60]:
A = A[..., tf.newaxis]
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[40],
         [21],
         [27]],

        [[26],
         [54],
         [34]],

        [[96],
         [77],
         [65]],

        [[67],
         [71],
         [27]]],


       [[[71],
         [45],
         [18]],

        [[74],
         [71],
         [94]],

        [[49],
         [56],
         [11]],

        [[53],
         [23],
         [26]]]])>

In [63]:
tf.expand_dims(A, axis=1)

<tf.Tensor: shape=(2, 1, 4, 3, 1), dtype=int64, numpy=
array([[[[[40],
          [21],
          [27]],

         [[26],
          [54],
          [34]],

         [[96],
          [77],
          [65]],

         [[67],
          [71],
          [27]]]],



       [[[[71],
          [45],
          [18]],

         [[74],
          [71],
          [94]],

         [[49],
          [56],
          [11]],

         [[53],
          [23],
          [26]]]]])>

In [64]:
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[40],
         [21],
         [27]],

        [[26],
         [54],
         [34]],

        [[96],
         [77],
         [65]],

        [[67],
         [71],
         [27]]],


       [[[71],
         [45],
         [18]],

        [[74],
         [71],
         [94]],

        [[49],
         [56],
         [11]],

        [[53],
         [23],
         [26]]]])>

In [65]:
A+5

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[ 45],
         [ 26],
         [ 32]],

        [[ 31],
         [ 59],
         [ 39]],

        [[101],
         [ 82],
         [ 70]],

        [[ 72],
         [ 76],
         [ 32]]],


       [[[ 76],
         [ 50],
         [ 23]],

        [[ 79],
         [ 76],
         [ 99]],

        [[ 54],
         [ 61],
         [ 16]],

        [[ 58],
         [ 28],
         [ 31]]]])>

In [66]:
A-10

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[30],
         [11],
         [17]],

        [[16],
         [44],
         [24]],

        [[86],
         [67],
         [55]],

        [[57],
         [61],
         [17]]],


       [[[61],
         [35],
         [ 8]],

        [[64],
         [61],
         [84]],

        [[39],
         [46],
         [ 1]],

        [[43],
         [13],
         [16]]]])>

In [67]:
A/2

<tf.Tensor: shape=(2, 4, 3, 1), dtype=float64, numpy=
array([[[[20. ],
         [10.5],
         [13.5]],

        [[13. ],
         [27. ],
         [17. ]],

        [[48. ],
         [38.5],
         [32.5]],

        [[33.5],
         [35.5],
         [13.5]]],


       [[[35.5],
         [22.5],
         [ 9. ]],

        [[37. ],
         [35.5],
         [47. ]],

        [[24.5],
         [28. ],
         [ 5.5]],

        [[26.5],
         [11.5],
         [13. ]]]])>

In [68]:
A*23

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[ 920],
         [ 483],
         [ 621]],

        [[ 598],
         [1242],
         [ 782]],

        [[2208],
         [1771],
         [1495]],

        [[1541],
         [1633],
         [ 621]]],


       [[[1633],
         [1035],
         [ 414]],

        [[1702],
         [1633],
         [2162]],

        [[1127],
         [1288],
         [ 253]],

        [[1219],
         [ 529],
         [ 598]]]])>

In [69]:
tf.multiply(A, 10)

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[400],
         [210],
         [270]],

        [[260],
         [540],
         [340]],

        [[960],
         [770],
         [650]],

        [[670],
         [710],
         [270]]],


       [[[710],
         [450],
         [180]],

        [[740],
         [710],
         [940]],

        [[490],
         [560],
         [110]],

        [[530],
         [230],
         [260]]]])>

In [70]:
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[40],
         [21],
         [27]],

        [[26],
         [54],
         [34]],

        [[96],
         [77],
         [65]],

        [[67],
         [71],
         [27]]],


       [[[71],
         [45],
         [18]],

        [[74],
         [71],
         [94]],

        [[49],
         [56],
         [11]],

        [[53],
         [23],
         [26]]]])>

In [71]:
A * A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[1600],
         [ 441],
         [ 729]],

        [[ 676],
         [2916],
         [1156]],

        [[9216],
         [5929],
         [4225]],

        [[4489],
         [5041],
         [ 729]]],


       [[[5041],
         [2025],
         [ 324]],

        [[5476],
         [5041],
         [8836]],

        [[2401],
         [3136],
         [ 121]],

        [[2809],
         [ 529],
         [ 676]]]])>

In [78]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[10,10,10],
                 [10,10,10],
                 ])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]], dtype=int32)>)

In [79]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

In [81]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

In [82]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [83]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [84]:
tf.reshape(X, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [85]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]], dtype=int32)>)

In [93]:
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

*   `tf.tensordot`
*   `tf.matmul`
*   `@`

