<a href="https://colab.research.google.com/github/realalyeasin/Deep-Learning/blob/main/TensorFlow_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Introducion to TensorFlow***
---

---



*   Intro
*   Info
*   Manipulating
*   Numpy
*   @tf.function
*   GPU







***Intro***

In [1]:
#Importing
import tensorflow as tf
print(tf.__version__)

2.8.0


***Creating tensors with tf.constant()***

In [2]:
scaler = tf.constant(120)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [3]:
scaler.ndim

0

In [4]:
vector = tf.constant([76,79,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([76, 79, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[263,726,917],[625,27,182]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[263, 726, 917],
       [625,  27, 182]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[11,12,13],
                       [71,52,43]],
                      [[22,44,36],
                       [22,54,32]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [71, 52, 43]],

       [[22, 44, 36],
        [22, 54, 32]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
x = tf.Variable([100,200,300])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300], dtype=int32)>

In [11]:
x[2].assign(250)
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 250], dtype=int32)>

***Random Tensor***

In [12]:
x1 = tf.random.Generator.from_seed(10)
x1 = x1.normal(shape=(2,1,4))
x2 = tf.random.Generator.from_seed(10)
x2 = x2.normal(shape=(2,1,4))

In [13]:
x1, x2, x1 == x2

(<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True]],
 
        [[ True,  True,  True,  True]]])>)

***Shuffle***

In [14]:
tf.random.set_seed(42)
tf.random.shuffle(x1)

<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
array([[[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],

       [[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]]],
      dtype=float32)>

In [15]:
tf.ones([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.zeros([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

***Numpy Array into Tensor***

In [17]:
import numpy as np
numpy_A = np.arange(1,20,2, dtype=np.int32)
numpy_A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int32)

In [18]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,5))

***Info***
* Shape
* Rank
* Axis
* Size

In [19]:
A = tf.ones(shape=[2,3,5,8])
A

<tf.Tensor: shape=(2, 3, 5, 8), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.,

In [20]:
print("Datatype", A.dtype)
print("Dimensions", A.ndim)
print("Shape", A.shape)
print("0 Axis", A.shape[0])
print("Last Axis", A.shape[-1])
print("Total Elements", tf.size(A))
print("Total Elements", tf.size(A).numpy())

Datatype <dtype: 'float32'>
Dimensions 4
Shape (2, 3, 5, 8)
0 Axis 2
Last Axis 8
Total Elements tf.Tensor(240, shape=(), dtype=int32)
Total Elements 240
