<a href="https://colab.research.google.com/github/realalyeasin/Deep-Learning/blob/main/TensorFlow_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Introducion to TensorFlow***
---

---



*   Intro
*   Info
*   Manipulating
*   Numpy
*   @tf.function
*   GPU







***Intro***

In [2]:
#Importing
import tensorflow as tf
print(tf.__version__)

2.8.0


***Creating tensors with tf.constant()***

In [3]:
scaler = tf.constant(120)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [4]:
scaler.ndim

0

In [5]:
vector = tf.constant([76,79,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([76, 79, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[263,726,917],[625,27,182]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[263, 726, 917],
       [625,  27, 182]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[11,12,13],
                       [71,52,43]],
                      [[22,44,36],
                       [22,54,32]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [71, 52, 43]],

       [[22, 44, 36],
        [22, 54, 32]]], dtype=int32)>

In [10]:
tensor.ndim

3

In [11]:
x = tf.Variable([100,200,300])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300], dtype=int32)>

In [12]:
x[2].assign(250)
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 250], dtype=int32)>

***Random Tensor***

In [13]:
x1 = tf.random.Generator.from_seed(10)
x1 = x1.normal(shape=(2,1,4))
x2 = tf.random.Generator.from_seed(10)
x2 = x2.normal(shape=(2,1,4))

In [14]:
x1, x2, x1 == x2

(<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
 array([[[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]],
 
        [[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True]],
 
        [[ True,  True,  True,  True]]])>)

***Shuffle***

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(x1)

<tf.Tensor: shape=(2, 1, 4), dtype=float32, numpy=
array([[[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],

       [[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ]]],
      dtype=float32)>

In [16]:
tf.ones([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

***Numpy Array into Tensor***

In [18]:
import numpy as np
numpy_A = np.arange(1,20,2, dtype=np.int32)
numpy_A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int32)

In [19]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,5))

***Info***
* Shape
* Rank
* Axis
* Size

In [20]:
A = tf.ones(shape=[2,3,5,8])
A

<tf.Tensor: shape=(2, 3, 5, 8), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.,

In [21]:
print("Datatype", A.dtype)
print("Dimensions", A.ndim)
print("Shape", A.shape)
print("0 Axis", A.shape[0])
print("Last Axis", A.shape[-1])
print("Total Elements", tf.size(A))
print("Total Elements", tf.size(A).numpy())

Datatype <dtype: 'float32'>
Dimensions 4
Shape (2, 3, 5, 8)
0 Axis 2
Last Axis 8
Total Elements tf.Tensor(240, shape=(), dtype=int32)
Total Elements 240


***Indexing***

In [22]:
a = np.random.randint(5,100, size=24)
tf.constant(a)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([53, 17, 54, 74, 60, 66, 46, 16, 26, 45, 18, 14,  5, 36, 49, 56, 32,
       82, 87, 56, 78, 80, 23, 56])>

In [23]:
a[:6]

array([53, 17, 54, 74, 60, 66])

In [24]:
A = tf.constant(a, shape=[2,4,3])
A

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[53, 17, 54],
        [74, 60, 66],
        [46, 16, 26],
        [45, 18, 14]],

       [[ 5, 36, 49],
        [56, 32, 82],
        [87, 56, 78],
        [80, 23, 56]]])>

In [25]:
A[:1,-1,:2]

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[45, 18]])>

In [26]:
A[:1, -2, -2]

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([16])>

In [27]:
A[:1, -2]

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[46, 16, 26]])>

In [28]:
A[:1,:,:1]

<tf.Tensor: shape=(1, 4, 1), dtype=int64, numpy=
array([[[53],
        [74],
        [46],
        [45]]])>

In [29]:
A[:,-1,-1]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([14, 56])>

In [30]:
A = A[..., tf.newaxis]
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[53],
         [17],
         [54]],

        [[74],
         [60],
         [66]],

        [[46],
         [16],
         [26]],

        [[45],
         [18],
         [14]]],


       [[[ 5],
         [36],
         [49]],

        [[56],
         [32],
         [82]],

        [[87],
         [56],
         [78]],

        [[80],
         [23],
         [56]]]])>

In [31]:
tf.expand_dims(A, axis=1)

<tf.Tensor: shape=(2, 1, 4, 3, 1), dtype=int64, numpy=
array([[[[[53],
          [17],
          [54]],

         [[74],
          [60],
          [66]],

         [[46],
          [16],
          [26]],

         [[45],
          [18],
          [14]]]],



       [[[[ 5],
          [36],
          [49]],

         [[56],
          [32],
          [82]],

         [[87],
          [56],
          [78]],

         [[80],
          [23],
          [56]]]]])>

In [32]:
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[53],
         [17],
         [54]],

        [[74],
         [60],
         [66]],

        [[46],
         [16],
         [26]],

        [[45],
         [18],
         [14]]],


       [[[ 5],
         [36],
         [49]],

        [[56],
         [32],
         [82]],

        [[87],
         [56],
         [78]],

        [[80],
         [23],
         [56]]]])>

In [33]:
A+5

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[58],
         [22],
         [59]],

        [[79],
         [65],
         [71]],

        [[51],
         [21],
         [31]],

        [[50],
         [23],
         [19]]],


       [[[10],
         [41],
         [54]],

        [[61],
         [37],
         [87]],

        [[92],
         [61],
         [83]],

        [[85],
         [28],
         [61]]]])>

In [34]:
A-10

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[43],
         [ 7],
         [44]],

        [[64],
         [50],
         [56]],

        [[36],
         [ 6],
         [16]],

        [[35],
         [ 8],
         [ 4]]],


       [[[-5],
         [26],
         [39]],

        [[46],
         [22],
         [72]],

        [[77],
         [46],
         [68]],

        [[70],
         [13],
         [46]]]])>

In [35]:
A/2

<tf.Tensor: shape=(2, 4, 3, 1), dtype=float64, numpy=
array([[[[26.5],
         [ 8.5],
         [27. ]],

        [[37. ],
         [30. ],
         [33. ]],

        [[23. ],
         [ 8. ],
         [13. ]],

        [[22.5],
         [ 9. ],
         [ 7. ]]],


       [[[ 2.5],
         [18. ],
         [24.5]],

        [[28. ],
         [16. ],
         [41. ]],

        [[43.5],
         [28. ],
         [39. ]],

        [[40. ],
         [11.5],
         [28. ]]]])>

In [36]:
A*23

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[1219],
         [ 391],
         [1242]],

        [[1702],
         [1380],
         [1518]],

        [[1058],
         [ 368],
         [ 598]],

        [[1035],
         [ 414],
         [ 322]]],


       [[[ 115],
         [ 828],
         [1127]],

        [[1288],
         [ 736],
         [1886]],

        [[2001],
         [1288],
         [1794]],

        [[1840],
         [ 529],
         [1288]]]])>

In [37]:
tf.multiply(A, 10)

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[530],
         [170],
         [540]],

        [[740],
         [600],
         [660]],

        [[460],
         [160],
         [260]],

        [[450],
         [180],
         [140]]],


       [[[ 50],
         [360],
         [490]],

        [[560],
         [320],
         [820]],

        [[870],
         [560],
         [780]],

        [[800],
         [230],
         [560]]]])>

In [38]:
A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[53],
         [17],
         [54]],

        [[74],
         [60],
         [66]],

        [[46],
         [16],
         [26]],

        [[45],
         [18],
         [14]]],


       [[[ 5],
         [36],
         [49]],

        [[56],
         [32],
         [82]],

        [[87],
         [56],
         [78]],

        [[80],
         [23],
         [56]]]])>

In [39]:
A * A

<tf.Tensor: shape=(2, 4, 3, 1), dtype=int64, numpy=
array([[[[2809],
         [ 289],
         [2916]],

        [[5476],
         [3600],
         [4356]],

        [[2116],
         [ 256],
         [ 676]],

        [[2025],
         [ 324],
         [ 196]]],


       [[[  25],
         [1296],
         [2401]],

        [[3136],
         [1024],
         [6724]],

        [[7569],
         [3136],
         [6084]],

        [[6400],
         [ 529],
         [3136]]]])>

In [40]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[10,10,10],
                 [10,10,10],
                 ])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]], dtype=int32)>)

In [41]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

In [42]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

In [43]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [44]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [45]:
tf.reshape(X, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [46]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]], dtype=int32)>)

In [47]:
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  30,  30],
       [ 70,  70,  70],
       [110, 110, 110]], dtype=int32)>

*   `tf.tensordot`
*   `tf.matmul`
*   `@`



***Datatype***

In [48]:
A = tf.constant([1.2, 2.3])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2.3], dtype=float32)>

In [50]:
tf.cast(A, dtype=tf.float16)


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 2.3], dtype=float16)>

***Aggregating***

In [52]:
C = np.random.randint(-100,100, size=50)
C

array([ 27, -76, -58,   9, -56, -57,  27,   3, -49, -23, -10, -93, -41,
       -97,  32, -89, -79, -79, -36, -41,  83,  23,  55,  87,  54, -10,
        98,  32,  60,   3, -19,  50,  36, -69,  56,  99, -43,  25, -82,
        67,  48, -37,  54, -80,  20,  44, -23,  79, -42,  12])

In [54]:
D = tf.constant(C, shape=(10,5))
D

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[ 27, -76, -58,   9, -56],
       [-57,  27,   3, -49, -23],
       [-10, -93, -41, -97,  32],
       [-89, -79, -79, -36, -41],
       [ 83,  23,  55,  87,  54],
       [-10,  98,  32,  60,   3],
       [-19,  50,  36, -69,  56],
       [ 99, -43,  25, -82,  67],
       [ 48, -37,  54, -80,  20],
       [ 44, -23,  79, -42,  12]])>

In [55]:
tf.abs(D)

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[27, 76, 58,  9, 56],
       [57, 27,  3, 49, 23],
       [10, 93, 41, 97, 32],
       [89, 79, 79, 36, 41],
       [83, 23, 55, 87, 54],
       [10, 98, 32, 60,  3],
       [19, 50, 36, 69, 56],
       [99, 43, 25, 82, 67],
       [48, 37, 54, 80, 20],
       [44, 23, 79, 42, 12]])>

In [56]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int64, numpy=-97>

In [57]:
np.min(D)

-97

In [58]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [59]:
np.max(D)

99

In [60]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int64, numpy=-2>

In [61]:
np.mean(D)

-2.12

In [62]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int64, numpy=-106>

In [63]:
np.sum(D)

-106

In [64]:
np.median(D)

3.0

In [65]:
import tensorflow_probability as tfp

In [66]:
tfp.stats.variance(D)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3204, 3543, 2530, 3507, 1592])>

In [68]:
tfp.stats.stddev(tf.cast(D, dtype=tf.float16))

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([56.62, 59.5 , 50.3 , 59.22, 39.88], dtype=float16)>

***Positional Maximum and Minimum***

In [70]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [71]:
C[tf.argmax(C)]

99

In [72]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [73]:
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [76]:
C[tf.argmin(C)]

-97

***Squeezing***

In [80]:
tf.random.set_seed(123)
E = tf.constant(tf.random.uniform(shape=[30]), shape=(1,3,1,2,5,1))
E

<tf.Tensor: shape=(1, 3, 1, 2, 5, 1), dtype=float32, numpy=
array([[[[[[0.12615311],
           [0.5727513 ],
           [0.2993133 ],
           [0.5461836 ],
           [0.7205157 ]],

          [[0.7889533 ],
           [0.3076812 ],
           [0.48171103],
           [0.6537752 ],
           [0.12099254]]]],



        [[[[0.36291742],
           [0.24489999],
           [0.22695613],
           [0.52010036],
           [0.86846626]],

          [[0.28618944],
           [0.49184704],
           [0.6749884 ],
           [0.44017053],
           [0.48929918]]]],



        [[[[0.8056352 ],
           [0.8974284 ],
           [0.636616  ],
           [0.50120056],
           [0.48389077]],

          [[0.7522563 ],
           [0.8064859 ],
           [0.4903134 ],
           [0.4176178 ],
           [0.9197507 ]]]]]], dtype=float32)>

In [81]:
tf.squeeze(E)

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0.12615311, 0.5727513 , 0.2993133 , 0.5461836 , 0.7205157 ],
        [0.7889533 , 0.3076812 , 0.48171103, 0.6537752 , 0.12099254]],

       [[0.36291742, 0.24489999, 0.22695613, 0.52010036, 0.86846626],
        [0.28618944, 0.49184704, 0.6749884 , 0.44017053, 0.48929918]],

       [[0.8056352 , 0.8974284 , 0.636616  , 0.50120056, 0.48389077],
        [0.7522563 , 0.8064859 , 0.4903134 , 0.4176178 , 0.9197507 ]]],
      dtype=float32)>

***One-Hot Encoding***

In [88]:
G = [0,2,3,4,5]
tf.one_hot(G, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [89]:
tf.one_hot(G, depth=5, on_value='Yes', off_value='Noo')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Yes', b'Noo', b'Noo', b'Noo', b'Noo'],
       [b'Noo', b'Noo', b'Yes', b'Noo', b'Noo'],
       [b'Noo', b'Noo', b'Noo', b'Yes', b'Noo'],
       [b'Noo', b'Noo', b'Noo', b'Noo', b'Yes'],
       [b'Noo', b'Noo', b'Noo', b'Noo', b'Noo']], dtype=object)>

In [90]:
tf.square(G)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  4,  9, 16, 25], dtype=int32)>

In [94]:
np.sqrt(G)

array([0.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [96]:
np.log(G)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 1.09861229, 1.38629436, 1.60943791])